namespace Andreas.PowerGrip.Shared.Linux.Enumerations;

public enum MediaKind
{
    [EnumMember(Value = "thumb")] ThumbDrive,
    [EnumMember(Value = "flash")] FlashDrive,
    [EnumMember(Value = "flash_cf")] CompactFlashDrive,
    [EnumMember(Value = "flash_ms")] MemoryStick,
    [EnumMember(Value = "flash_sm")] SmartMedia,
    [EnumMember(Value = "flash_sd")] SecureDigital,
    [EnumMember(Value = "flash_sdhc")] SecureDigitalHighCap,
    [EnumMember(Value = "flash_sdxc")] SecureDigitalExtCap,
    [EnumMember(Value = "flash_sdio")] SecureDigitalIO,
    [EnumMember(Value = "flash_sd_combo")] SecureDigitalCombo,
    [EnumMember(Value = "flash_mmc")] MultiMediaCard,
    [EnumMember(Value = "floppy")] FloppyDisk,
    [EnumMember(Value = "floppy_zip")] ZipDisk,
    [EnumMember(Value = "floppy_jaz")] JazDisk,
    [EnumMember(Value = "optical")] OpticalDisk,
    [EnumMember(Value = "optical_cd")] CompactDisk,
    [EnumMember(Value = "optical_cd_r")] CdRecordable,
    [EnumMember(Value = "optical_cd_rw")] CdRewritable,
    [EnumMember(Value = "optical_dvd")] DigitalVersatileDisk,
    [EnumMember(Value = "optical_dvd_r")] DvdRecordable,
    [EnumMember(Value = "optical_dvd_rw")] DvdRewritable,
    [EnumMember(Value = "optical_dvd_ram")] DvdRam,
    [EnumMember(Value = "optical_dvd_plus_r")] DvdPlusRecordable,
    [EnumMember(Value = "optical_dvd_plus_rw")] DvdPlusRewritable,
    [EnumMember(Value = "optical_dvd_plus_r_dl")] DvdPlusRecordableDualLayer,
    [EnumMember(Value = "optical_dvd_plus_rw_dl")] DvdPlusRewritableDualLayer,
    [EnumMember(Value = "optical_bd")] BluRay,
    [EnumMember(Value = "optical_bd_r")] BluRayRecordable,
    [EnumMember(Value = "optical_bd_rw")] BluRayRewritable,
    [EnumMember(Value = "optical_hddvd")] HdDvd,
    [EnumMember(Value = "optical_hddvd_r")] HdDvdRecordable,
    [EnumMember(Value = "optical_hddvd_rw")] HdDvdRewritable,
    [EnumMember(Value = "optical_mo")] Magneto,
    [EnumMember(Value = "optical_mrw")] MountRainerRead,
    [EnumMember(Value = "optical_mrw_w")] MountRainerWrite,
    [EnumMember(Value = "unknown")] Unknown
}