namespace Andreas.PowerGrip.Shared.Types.Auth;

public static class AppRoles
{
    /// <summary>
    /// Regular administrator of the system.
    /// </summary>
    public const string Admin = "admin";

    /// <summary>
    /// The user can do anything! Even adding administrators.
    /// Should be used in those "oh-shit" situations.
    /// Super users are generated by PowerGrip on startup via
    /// The configuration only.
    /// </summary>
    public const string SuperUser = "su";

    /// <summary>
    /// Returns an array of known user roles.
    /// </summary>
    /// <returns>Array of <see cref="string"/>s that contains the roles defined in the system.</returns>
    public static string[] KnownRoles() =>
    [
        Admin,
        SuperUser
    ];

    /// <summary>
    /// Checks wether the role is defined or not.
    /// </summary>
    /// <param name="role">The role string to check for</param>
    /// <returns><see cref="true"/> if the role is defined, <see cref="false"/> otherwise.</returns>
    public static bool IsKnown(string role)
        => KnownRoles().Any(role.SameAs);
}